// Code generated by generate_types.go; DO NOT EDIT.

package greenpass

import (
	"fmt"
)

type DiseaseAgentTargeted string

func (this DiseaseAgentTargeted) String() string {
	name, ok := diseaseAgentTargetedNames[this]
	if !ok {
		return fmt.Sprintf("unknown('%s')", this)
	}
	return name
}

var diseaseAgentTargetedNames = map[DiseaseAgentTargeted]string{
	"840539006": "COVID-19",
}

type Country2Codes string

func (this Country2Codes) String() string {
	name, ok := country2CodesNames[this]
	if !ok {
		return fmt.Sprintf("unknown('%s')", this)
	}
	return name
}

var country2CodesNames = map[Country2Codes]string{
	"AE": "United Arab Emirates",
	"RS": "Serbia",
	"SX": "Sint Maarten (Dutch part)",
	"CF": "Central African Republic",
	"KI": "Kiribati",
	"SG": "Singapore",
	"TG": "Togo",
	"PF": "French Polynesia",
	"TF": "French Southern Territories",
	"AT": "Austria",
	"CU": "Cuba",
	"GL": "Greenland",
	"HT": "Haiti",
	"LT": "Lithuania",
	"BT": "Bhutan",
	"HR": "Croatia",
	"NG": "Nigeria",
	"RW": "Rwanda",
	"TH": "Thailand",
	"AG": "Antigua and Barbuda",
	"AI": "Anguilla",
	"BM": "Bermuda",
	"VE": "Venezuela, Bolivarian Republic of",
	"ZW": "Zimbabwe",
	"MY": "Malaysia",
	"BA": "Bosnia and Herzegovina",
	"BE": "Belgium",
	"FM": "Micronesia, Federated States of",
	"IN": "India",
	"KZ": "Kazakhstan",
	"AZ": "Azerbaijan",
	"LB": "Lebanon",
	"SH": "Saint Helena, Ascension and Tristan da Cunha",
	"BH": "Bahrain",
	"DM": "Dominica",
	"MA": "Morocco",
	"AS": "American Samoa",
	"GM": "Gambia",
	"LK": "Sri Lanka",
	"SZ": "Swaziland",
	"TM": "Turkmenistan",
	"TO": "Tonga",
	"SL": "Sierra Leone",
	"UZ": "Uzbekistan",
	"CH": "Switzerland",
	"GT": "Guatemala",
	"KM": "Comoros",
	"KY": "Cayman Islands",
	"SI": "Slovenia",
	"BD": "Bangladesh",
	"CK": "Cook Islands",
	"FK": "Falkland Islands (Malvinas)",
	"VN": "Viet Nam",
	"AO": "Angola",
	"GU": "Guam",
	"HN": "Honduras",
	"UY": "Uruguay",
	"VA": "Holy See",
	"LY": "Libya",
	"MR": "Mauritania",
	"NE": "Niger",
	"ZA": "South Africa",
	"CD": "Congo, the Democratic Republic of the",
	"MF": "Saint Martin (French part)",
	"DJ": "Djibouti",
	"VC": "Saint Vincent and the Grenadines",
	"BZ": "Belize",
	"DO": "Dominican Republic",
	"ES": "Spain",
	"NF": "Norfolk Island",
	"EE": "Estonia",
	"IE": "Ireland",
	"MH": "Marshall Islands",
	"MQ": "Martinique",
	"MZ": "Mozambique",
	"SD": "Sudan",
	"SN": "Senegal",
	"BG": "Bulgaria",
	"CO": "Colombia",
	"FI": "Finland",
	"HK": "Hong Kong",
	"IR": "Iran, Islamic Republic of",
	"AM": "Armenia",
	"DE": "Germany",
	"GH": "Ghana",
	"GQ": "Equatorial Guinea",
	"PE": "Peru",
	"SS": "South Sudan",
	"CN": "China",
	"EH": "Western Sahara",
	"GB": "United Kingdom of Great Britain and Northern Ireland",
	"MD": "Moldova, Republic of",
	"MN": "Mongolia",
	"BV": "Bouvet Island",
	"IT": "Italy",
	"NO": "Norway",
	"TC": "Turks and Caicos Islands",
	"NA": "Namibia",
	"PK": "Pakistan",
	"SB": "Solomon Islands",
	"ID": "Indonesia",
	"KP": "Korea, Democratic People''s Republic of",
	"NP": "Nepal",
	"TN": "Tunisia",
	"UG": "Uganda",
	"PH": "Philippines",
	"AD": "Andorra",
	"DZ": "Algeria",
	"MW": "Malawi",
	"NR": "Nauru",
	"NZ": "New Zealand",
	"ME": "Montenegro",
	"MK": "Macedonia, the former Yugoslav Republic of",
	"VG": "Virgin Islands, British",
	"LV": "Latvia",
	"TZ": "Tanzania, United Republic of",
	"PN": "Pitcairn",
	"SK": "Slovakia",
	"AL": "Albania",
	"AU": "Australia",
	"BO": "Bolivia, Plurinational State of",
	"GW": "Guinea-Bissau",
	"KW": "Kuwait",
	"AQ": "Antarctica",
	"BS": "Bahamas",
	"CG": "Congo",
	"GS": "South Georgia and the South Sandwich Islands",
	"PG": "Papua New Guinea",
	"RU": "Russian Federation",
	"VU": "Vanuatu",
	"CC": "Cocos (Keeling) Islands",
	"EC": "Ecuador",
	"GY": "Guyana",
	"LC": "Saint Lucia",
	"RO": "Romania",
	"CV": "Cabo Verde",
	"CX": "Christmas Island",
	"IO": "British Indian Ocean Territory",
	"MO": "Macao",
	"OM": "Oman",
	"CW": "Curaçao",
	"GR": "Greece",
	"TR": "Turkey",
	"WS": "Samoa",
	"GD": "Grenada",
	"LU": "Luxembourg",
	"MU": "Mauritius",
	"LA": "Lao People''s Democratic Republic",
	"NL": "Netherlands",
	"NU": "Niue",
	"PL": "Poland",
	"YE": "Yemen",
	"AF": "Afghanistan",
	"EG": "Egypt",
	"FJ": "Fiji",
	"IL": "Israel",
	"SO": "Somalia",
	"CL": "Chile",
	"LI": "Liechtenstein",
	"MX": "Mexico",
	"QA": "Qatar",
	"SC": "Seychelles",
	"SM": "San Marino",
	"BY": "Belarus",
	"JO": "Jordan",
	"MP": "Northern Mariana Islands",
	"PS": "Palestine, State of",
	"RE": "Réunion",
	"TT": "Trinidad and Tobago",
	"SY": "Syrian Arab Republic",
	"BI": "Burundi",
	"GI": "Gibraltar",
	"IM": "Isle of Man",
	"KN": "Saint Kitts and Nevis",
	"SR": "Suriname",
	"CM": "Cameroon",
	"GN": "Guinea",
	"TL": "Timor-Leste",
	"BF": "Burkina Faso",
	"GF": "French Guiana",
	"HU": "Hungary",
	"MC": "Monaco",
	"AR": "Argentina",
	"PT": "Portugal",
	"AW": "Aruba",
	"HM": "Heard Island and McDonald Islands",
	"ZM": "Zambia",
	"ST": "Sao Tome and Principe",
	"TV": "Tuvalu",
	"AX": "Åland Islands",
	"CI": "Côte d''Ivoire",
	"CR": "Costa Rica",
	"GE": "Georgia",
	"PW": "Palau",
	"BB": "Barbados",
	"CY": "Cyprus",
	"JM": "Jamaica",
	"MT": "Malta",
	"WF": "Wallis and Futuna",
	"CA": "Canada",
	"TW": "Taiwan, Province of China",
	"BR": "Brazil",
	"FO": "Faroe Islands",
	"FR": "France",
	"BJ": "Benin",
	"YT": "Mayotte",
	"JP": "Japan",
	"KE": "Kenya",
	"MM": "Myanmar",
	"PY": "Paraguay",
	"KG": "Kyrgyzstan",
	"PM": "Saint Pierre and Miquelon",
	"SV": "El Salvador",
	"GP": "Guadeloupe",
	"PR": "Puerto Rico",
	"SJ": "Svalbard and Jan Mayen",
	"TD": "Chad",
	"BN": "Brunei Darussalam",
	"BW": "Botswana",
	"IS": "Iceland",
	"KH": "Cambodia",
	"NI": "Nicaragua",
	"UA": "Ukraine",
	"BQ": "Bonaire, Sint Eustatius and Saba",
	"ER": "Eritrea",
	"JE": "Jersey",
	"UM": "United States Minor Outlying Islands",
	"IQ": "Iraq",
	"KR": "Korea, Republic of",
	"PA": "Panama",
	"SE": "Sweden",
	"US": "United States of America",
	"BL": "Saint Barthélemy",
	"CZ": "Czechia",
	"NC": "New Caledonia",
	"TJ": "Tajikistan",
	"MV": "Maldives",
	"SA": "Saudi Arabia",
	"VI": "Virgin Islands,",
	"DK": "Denmark",
	"GG": "Guernsey",
	"LR": "Liberia",
	"LS": "Lesotho",
	"MS": "Montserrat",
	"ET": "Ethiopia",
	"GA": "Gabon",
	"MG": "Madagascar",
	"ML": "Mali",
	"TK": "Tokelau",
}

type VaccineProphylaxis string

func (this VaccineProphylaxis) String() string {
	name, ok := vaccineProphylaxisNames[this]
	if !ok {
		return fmt.Sprintf("unknown('%s')", this)
	}
	return name
}

var vaccineProphylaxisNames = map[VaccineProphylaxis]string{
	"J07BX03":    "covid-19 vaccines",
	"1119349007": "SARS-CoV-2 mRNA vaccine",
	"1119305005": "SARS-CoV-2 antigen vaccine",
}

type VaccineMedicinalProduct string

func (this VaccineMedicinalProduct) String() string {
	name, ok := vaccineMedicinalProductNames[this]
	if !ok {
		return fmt.Sprintf("unknown('%s')", this)
	}
	return name
}

var vaccineMedicinalProductNames = map[VaccineMedicinalProduct]string{
	"EU/1/20/1525":                     "COVID-19 Vaccine Janssen",
	"Sputnik-V":                        "Sputnik-V",
	"EpiVacCorona":                     "EpiVacCorona",
	"BBIBP-CorV":                       "BBIBP-CorV",
	"Inactivated-SARS-CoV-2-Vero-Cell": "Inactivated SARS-CoV-2 (Vero Cell)",
	"Covaxin":                          "Covaxin (also known as BBV152 A, B, C)",
	"EU/1/21/1529":                     "Vaxzevria",
	"EU/1/20/1507":                     "COVID-19 Vaccine Moderna",
	"CVnCoV":                           "CVnCoV",
	"Convidecia":                       "Convidecia",
	"CoronaVac":                        "CoronaVac",
	"EU/1/20/1528":                     "Comirnaty",
}

type VaccineMahManf string

func (this VaccineMahManf) String() string {
	name, ok := vaccineMahManfNames[this]
	if !ok {
		return fmt.Sprintf("unknown('%s')", this)
	}
	return name
}

var vaccineMahManfNames = map[VaccineMahManf]string{
	"ORG-100030215":               "Biontech Manufacturing GmbH",
	"ORG-100006270":               "Curevac AG",
	"ORG-100031184":               "Moderna Biotech Spain S.L.",
	"ORG-100010771":               "Sinopharm Weiqida Europe Pharmaceutical s.r.o. - Prague location",
	"ORG-100024420":               "Sinopharm Zhijun (Shenzhen) Pharmaceutical Co. Ltd. - Shenzhen location",
	"Vector-Institute":            "Vector Institute",
	"Sinovac-Biotech":             "Sinovac Biotech",
	"Bharat-Biotech":              "Bharat Biotech",
	"ORG-100001699":               "AstraZeneca AB",
	"ORG-100001417":               "Janssen-Cilag International",
	"ORG-100013793":               "CanSino Biologics",
	"ORG-100020693":               "China Sinopharm International Corp. - Beijing location",
	"ORG-100032020":               "Novavax CZ AS",
	"Gamaleya-Research-Institute": "Gamaleya Research Institute",
}
